import os

# Function App environment variables
CLIENT_ID = os.environ["APP_REGISTRATION_CLIENT_ID"]
CLIENT_SECRECT = os.environ["APP_REGISTRATION_CLIENT_SECRECT"]
TENANT_ID = os.environ["APP_REGISTRATION_TENANT_ID"]
NOTIFICATION_URL = os.environ["API_NOTIFICATION_URL"]
INGESTFUNC_URL = os.environ['INGESTFUNC_URL']
INGEST_STRING = os.environ['INGEST_STRING']

# Service Bus environment variables
SB_CONNECTION_STR = os.environ["SERVICE_BUS_CONNECTION_STR"]
TOPIC_NAME = os.environ["SERVICE_BUS_TOPIC_NAME"]
SUBSCRIPTION_NAME = os.environ["SERVICE_BUS_SUBSCRIPTION_NAME"]

# Event Hub environment variables
EH_CALLS_CONNECTION_STR = os.environ["EVENT_HUB_CALLS_CONNECTION_STR"]
EH_CALLS_NAME = os.environ["EVENT_HUB_CALLS_NAME"]
EH_PARTICIPANTS_CONNECTION_STR = os.environ["EVENT_HUB_PARTICIPANTS_CONNECTION_STR"]
EH_PARTICIPANTS_NAME = os.environ["EVENT_HUB_PARTICIPANTS_NAME"]
EH_SESSIONS_CONNECTION_STR = os.environ["EVENT_HUB_SESSIONS_CONNECTION_STR"]
EH_SESSIONS_NAME = os.environ["EVENT_HUB_SESSIONS_NAME"]